export interface SourceFilterValue {
  readonly value: string;
  readonly displayName: string;
}

export interface SourceCatalogEntry {
  readonly id: string;
  readonly displayName: string;
  readonly filterKey: string;
  readonly filterValues: ReadonlyArray<SourceFilterValue>;
}

const ARXIV_FILTER_VALUES: ReadonlyArray<SourceFilterValue> = [
  { value: "arxiv:cs.AI", displayName: "Artificial Intelligence" },
  { value: "arxiv:cs.AR", displayName: "Hardware Architecture" },
  { value: "arxiv:cs.CC", displayName: "Computational Complexity" },
  { value: "arxiv:cs.CE", displayName: "Computational Engineering, Finance, and Science" },
  { value: "arxiv:cs.CG", displayName: "Computational Geometry" },
  { value: "arxiv:cs.CL", displayName: "Computation and Language" },
  { value: "arxiv:cs.CR", displayName: "Cryptography and Security" },
  { value: "arxiv:cs.CV", displayName: "Computer Vision and Pattern Recognition" },
  { value: "arxiv:cs.CY", displayName: "Computers and Society" },
  { value: "arxiv:cs.DB", displayName: "Databases" },
  { value: "arxiv:cs.DC", displayName: "Distributed, Parallel, and Cluster Computing" },
  { value: "arxiv:cs.DL", displayName: "Digital Libraries" },
  { value: "arxiv:cs.DM", displayName: "Discrete Mathematics" },
  { value: "arxiv:cs.DS", displayName: "Data Structures and Algorithms" },
  { value: "arxiv:cs.ET", displayName: "Emerging Technologies" },
  { value: "arxiv:cs.FL", displayName: "Formal Languages and Automata Theory" },
  { value: "arxiv:cs.GL", displayName: "General Literature" },
  { value: "arxiv:cs.GR", displayName: "Graphics" },
  { value: "arxiv:cs.GT", displayName: "Computer Science and Game Theory" },
  { value: "arxiv:cs.HC", displayName: "Human-Computer Interaction" },
  { value: "arxiv:cs.IR", displayName: "Information Retrieval" },
  { value: "arxiv:cs.IT", displayName: "Information Theory" },
  { value: "arxiv:cs.LG", displayName: "Machine Learning" },
  { value: "arxiv:cs.LO", displayName: "Logic in Computer Science" },
  { value: "arxiv:cs.MA", displayName: "Multiagent Systems" },
  { value: "arxiv:cs.MM", displayName: "Multimedia" },
  { value: "arxiv:cs.MS", displayName: "Mathematical Software" },
  { value: "arxiv:cs.NA", displayName: "Numerical Analysis" },
  { value: "arxiv:cs.NE", displayName: "Neural and Evolutionary Computing" },
  { value: "arxiv:cs.NI", displayName: "Networking and Internet Architecture" },
  { value: "arxiv:cs.OH", displayName: "Other Computer Science" },
  { value: "arxiv:cs.OS", displayName: "Operating Systems" },
  { value: "arxiv:cs.PF", displayName: "Performance" },
  { value: "arxiv:cs.PL", displayName: "Programming Languages" },
  { value: "arxiv:cs.RO", displayName: "Robotics" },
  { value: "arxiv:cs.SC", displayName: "Symbolic Computation" },
  { value: "arxiv:cs.SD", displayName: "Sound" },
  { value: "arxiv:cs.SE", displayName: "Software Engineering" },
  { value: "arxiv:cs.SI", displayName: "Social and Information Networks" },
  { value: "arxiv:cs.SY", displayName: "Systems and Control" },
  { value: "arxiv:econ.EM", displayName: "Econometrics" },
  { value: "arxiv:econ.GN", displayName: "General Economics" },
  { value: "arxiv:econ.TH", displayName: "Theoretical Economics" },
  { value: "arxiv:eess.AS", displayName: "Audio and Speech Processing" },
  { value: "arxiv:eess.IV", displayName: "Image and Video Processing" },
  { value: "arxiv:eess.SP", displayName: "Signal Processing" },
  { value: "arxiv:eess.SY", displayName: "Systems and Control" },
  { value: "arxiv:math.AC", displayName: "Commutative Algebra" },
  { value: "arxiv:math.AG", displayName: "Algebraic Geometry" },
  { value: "arxiv:math.AP", displayName: "Analysis of PDEs" },
  { value: "arxiv:math.AT", displayName: "Algebraic Topology" },
  { value: "arxiv:math.CA", displayName: "Classical Analysis and ODEs" },
  { value: "arxiv:math.CO", displayName: "Combinatorics" },
  { value: "arxiv:math.CT", displayName: "Category Theory" },
  { value: "arxiv:math.CV", displayName: "Complex Variables" },
  { value: "arxiv:math.DG", displayName: "Differential Geometry" },
  { value: "arxiv:math.DS", displayName: "Dynamical Systems" },
  { value: "arxiv:math.FA", displayName: "Functional Analysis" },
  { value: "arxiv:math.GM", displayName: "General Mathematics" },
  { value: "arxiv:math.GN", displayName: "General Topology" },
  { value: "arxiv:math.GR", displayName: "Group Theory" },
  { value: "arxiv:math.GT", displayName: "Geometric Topology" },
  { value: "arxiv:math.HO", displayName: "History and Overview" },
  { value: "arxiv:math.IT", displayName: "Information Theory" },
  { value: "arxiv:math.KT", displayName: "K-Theory and Homology" },
  { value: "arxiv:math.LO", displayName: "Logic" },
  { value: "arxiv:math.MG", displayName: "Metric Geometry" },
  { value: "arxiv:math.MP", displayName: "Mathematical Physics" },
  { value: "arxiv:math.NA", displayName: "Numerical Analysis" },
  { value: "arxiv:math.NT", displayName: "Number Theory" },
  { value: "arxiv:math.OA", displayName: "Operator Algebras" },
  { value: "arxiv:math.OC", displayName: "Optimization and Control" },
  { value: "arxiv:math.PR", displayName: "Probability" },
  { value: "arxiv:math.QA", displayName: "Quantum Algebra" },
  { value: "arxiv:math.RA", displayName: "Rings and Algebras" },
  { value: "arxiv:math.RT", displayName: "Representation Theory" },
  { value: "arxiv:math.SG", displayName: "Symplectic Geometry" },
  { value: "arxiv:math.SP", displayName: "Spectral Theory" },
  { value: "arxiv:math.ST", displayName: "Statistics Theory" },
  { value: "arxiv:astro-ph.CO", displayName: "Cosmology and Nongalactic Astrophysics" },
  { value: "arxiv:astro-ph.EP", displayName: "Earth and Planetary Astrophysics" },
  { value: "arxiv:astro-ph.GA", displayName: "Astrophysics of Galaxies" },
  { value: "arxiv:astro-ph.HE", displayName: "High Energy Astrophysical Phenomena" },
  { value: "arxiv:astro-ph.IM", displayName: "Instrumentation and Methods for Astrophysics" },
  { value: "arxiv:astro-ph.SR", displayName: "Solar and Stellar Astrophysics" },
  { value: "arxiv:cond-mat.dis-nn", displayName: "Disordered Systems and Neural Networks" },
  { value: "arxiv:cond-mat.mes-hall", displayName: "Mesoscale and Nanoscale Physics" },
  { value: "arxiv:cond-mat.mtrl-sci", displayName: "Materials Science" },
  { value: "arxiv:cond-mat.other", displayName: "Other Condensed Matter" },
  { value: "arxiv:cond-mat.quant-gas", displayName: "Quantum Gases" },
  { value: "arxiv:cond-mat.soft", displayName: "Soft Condensed Matter" },
  { value: "arxiv:cond-mat.stat-mech", displayName: "Statistical Mechanics" },
  { value: "arxiv:cond-mat.str-el", displayName: "Strongly Correlated Electrons" },
  { value: "arxiv:cond-mat.supr-con", displayName: "Superconductivity" },
  { value: "arxiv:gr-qc", displayName: "General Relativity and Quantum Cosmology" },
  { value: "arxiv:hep-ex", displayName: "High Energy Physics - Experiment" },
  { value: "arxiv:hep-lat", displayName: "High Energy Physics - Lattice" },
  { value: "arxiv:hep-ph", displayName: "High Energy Physics - Phenomenology" },
  { value: "arxiv:hep-th", displayName: "High Energy Physics - Theory" },
  { value: "arxiv:math-ph", displayName: "Mathematical Physics" },
  { value: "arxiv:nlin.AO", displayName: "Adaptation and Self-Organizing Systems" },
  { value: "arxiv:nlin.CD", displayName: "Chaotic Dynamics" },
  { value: "arxiv:nlin.CG", displayName: "Cellular Automata and Lattice Gases" },
  { value: "arxiv:nlin.PS", displayName: "Pattern Formation and Solitons" },
  { value: "arxiv:nlin.SI", displayName: "Exactly Solvable and Integrable Systems" },
  { value: "arxiv:nucl-ex", displayName: "Nuclear Experiment" },
  { value: "arxiv:nucl-th", displayName: "Nuclear Theory" },
  { value: "arxiv:physics.acc-ph", displayName: "Accelerator Physics" },
  { value: "arxiv:physics.ao-ph", displayName: "Atmospheric and Oceanic Physics" },
  { value: "arxiv:physics.app-ph", displayName: "Applied Physics" },
  { value: "arxiv:physics.atm-clus", displayName: "Atomic and Molecular Clusters" },
  { value: "arxiv:physics.atom-ph", displayName: "Atomic Physics" },
  { value: "arxiv:physics.bio-ph", displayName: "Biological Physics" },
  { value: "arxiv:physics.chem-ph", displayName: "Chemical Physics" },
  { value: "arxiv:physics.class-ph", displayName: "Classical Physics" },
  { value: "arxiv:physics.comp-ph", displayName: "Computational Physics" },
  { value: "arxiv:physics.data-an", displayName: "Data Analysis, Statistics and Probability" },
  { value: "arxiv:physics.ed-ph", displayName: "Physics Education" },
  { value: "arxiv:physics.flu-dyn", displayName: "Fluid Dynamics" },
  { value: "arxiv:physics.gen-ph", displayName: "General Physics" },
  { value: "arxiv:physics.geo-ph", displayName: "Geophysics" },
  { value: "arxiv:physics.hist-ph", displayName: "History and Philosophy of Physics" },
  { value: "arxiv:physics.ins-det", displayName: "Instrumentation and Detectors" },
  { value: "arxiv:physics.med-ph", displayName: "Medical Physics" },
  { value: "arxiv:physics.optics", displayName: "Optics" },
  { value: "arxiv:physics.plasm-ph", displayName: "Plasma Physics" },
  { value: "arxiv:physics.pop-ph", displayName: "Popular Physics" },
  { value: "arxiv:physics.soc-ph", displayName: "Physics and Society" },
  { value: "arxiv:physics.space-ph", displayName: "Space Physics" },
  { value: "arxiv:quant-ph", displayName: "Quantum Physics" },
  { value: "arxiv:q-bio.BM", displayName: "Biomolecules" },
  { value: "arxiv:q-bio.CB", displayName: "Cell Behavior" },
  { value: "arxiv:q-bio.GN", displayName: "Genomics" },
  { value: "arxiv:q-bio.MN", displayName: "Molecular Networks" },
  { value: "arxiv:q-bio.NC", displayName: "Neurons and Cognition" },
  { value: "arxiv:q-bio.OT", displayName: "Other Quantitative Biology" },
  { value: "arxiv:q-bio.PE", displayName: "Populations and Evolution" },
  { value: "arxiv:q-bio.QM", displayName: "Quantitative Methods" },
  { value: "arxiv:q-bio.SC", displayName: "Subcellular Processes" },
  { value: "arxiv:q-bio.TO", displayName: "Tissues and Organs" },
  { value: "arxiv:q-fin.CP", displayName: "Computational Finance" },
  { value: "arxiv:q-fin.EC", displayName: "Economics" },
  { value: "arxiv:q-fin.GN", displayName: "General Finance" },
  { value: "arxiv:q-fin.MF", displayName: "Mathematical Finance" },
  { value: "arxiv:q-fin.PM", displayName: "Portfolio Management" },
  { value: "arxiv:q-fin.PR", displayName: "Pricing of Securities" },
  { value: "arxiv:q-fin.RM", displayName: "Risk Management" },
  { value: "arxiv:q-fin.ST", displayName: "Statistical Finance" },
  { value: "arxiv:q-fin.TR", displayName: "Trading and Market Microstructure" },
  { value: "arxiv:stat.AP", displayName: "Applications" },
  { value: "arxiv:stat.CO", displayName: "Computation" },
  { value: "arxiv:stat.ME", displayName: "Methodology" },
  { value: "arxiv:stat.ML", displayName: "Machine Learning" },
  { value: "arxiv:stat.OT", displayName: "Other Statistics" },
  { value: "arxiv:stat.TH", displayName: "Statistics Theory" },
];

export const SOURCES: ReadonlyArray<SourceCatalogEntry> = [
  {
    id: "arxiv",
    displayName: "arXiv",
    filterKey: "category",
    filterValues: ARXIV_FILTER_VALUES,
  },
];

const KNOWN_FILTER_VALUES: ReadonlySet<string> = new Set(
  SOURCES.flatMap((s) => s.filterValues.map((f) => f.value)),
);

export function isKnownSourceFilter(value: string): boolean {
  return KNOWN_FILTER_VALUES.has(value);
}

export function arxivCategoryFromFilter(value: string): string | null {
  if (!value.startsWith("arxiv:")) return null;
  return value.slice("arxiv:".length);
}
